### ISSUE TITLE
installation instructions: Add reminder to "activate" the conda environment

### ISSUE THREAD

**Issue by cpsarason** [cormorack/visualoceanpy#6]
Should add:
$ source activate vizocean

just before the pip install line in README.md

**Comment by lsetiawan** [comment]
How about creating a pull request to have this change in there? :wink:

**Comment by cpsarason** [comment]
Heh. Fair enough Sensei.

**Comment by lsetiawan** [comment]
#7 Resolves this issue and examples have also been added. Thanks so much @cpsarason!
